Repository Team-Wordi/Wordi, pull requests merged in 2021-11, with the labels that each got.

#41 [FE] ProfileCard 컴포넌트 추가 (MainPage)
  src/components/Main/ProfileCard.tsx
  src/components/common/ProfileImage.tsx
Labels: 🚖 Feature, 🌐 FE, ⚙ Component

#42 Feat: [#35] TopNavbar 컴포넌트 추가 (common)
  src/assets/icons/notification_on.svg
  src/components/common/TopNavbar.tsx
  src/components/icon/ActiveNoficiationIcon.tsx
  src/components/icon/HamburgerIcon.tsx
Labels: 🚖 Feature, 🌐 FE, ⚙ Component

#43 Feat: [#34] Footer 컴포넌트 추가
  src/App.tsx
  src/components/Main/Footer.tsx
  src/styles/Theme.ts
Labels: 🚖 Feature, 🌐 FE, ⚙ Component

#44 Feat: [#37] Carousel 컴포넌트 추가 (공통)
  package-lock.json
  package.json
  src/components/common/Carousel.tsx
  src/components/common/CarouselCard.tsx
  src/index.tsx
Labels: 🚖 Feature, 🌐 FE, ⚙ Component

#47 Feat: [#45] Flag 컴포넌트 추가
  src/assets/img/UK.png
  src/components/Main/Flag.tsx
Labels: 🚖 Feature, 🌐 FE, ⚙ Component

#50 Task/36
  src/App.tsx
  src/assets/icons/flat_dot.svg
  src/assets/icons/love.svg
  src/components/Main/Banners.tsx
  src/components/Main/Body.tsx
  src/components/Main/Countries.tsx
  src/components/Main/Flag.tsx
  src/components/Main/Footer.tsx
  src/components/Main/Header.tsx
  src/components/Main/MentiReviewCard.tsx
  src/components/Main/MentiReviews.tsx
  src/components/Main/MentorTips.tsx
  src/components/Main/PopularMentors.tsx
  src/components/Main/ProfileCard.tsx
  src/components/MentorReview/Introduction.tsx
  src/components/common/Banner.tsx
  src/components/common/BottomTabBar.tsx
  src/components/common/Carousel.tsx
  src/components/common/CarouselCard.tsx
  src/components/common/ProfileImage.tsx
  src/components/common/Title.tsx
  src/components/icon/ActiveReviewIcon.tsx
  src/components/icon/FlatDotIcon.tsx
  src/components/icon/LoveIcon.tsx
  src/components/icon/ReviewIcon.tsx
  src/pages/ApplicationPage.tsx
  src/pages/MainPage.tsx
  src/pages/MentorColumnPage.tsx
  src/pages/MentorReviewPage.tsx
  src/styles/GlobalStyles.ts
  src/styles/Theme.ts
Labels: 🚖 Feature, 🌐 FE, ⚙ Component

#51 Feat: [#49] MainCarouselCard 컴포넌트 추가
  src/assets/img/the_world.png
  src/components/Main/MainCarouselCard.tsx
  src/components/common/Carousel.tsx
  src/components/common/CarouselCard.tsx
  src/styles/Theme.ts
Labels: 🚖 Feature, 🌐 FE, ⚙ Component

#54 Feat: [#53] Spring Boot 프로젝트 등록 및 환경설정
  server/index.js
  server/wordi/.gitignore
  server/wordi/build.gradle
  server/wordi/gradle/wrapper/gradle-wrapper.jar
  server/wordi/gradle/wrapper/gradle-wrapper.properties
  server/wordi/gradlew
  server/wordi/gradlew.bat
  server/wordi/settings.gradle
  server/wordi/src/main/java/com/pm/wordi/WordiApplication.java
  server/wordi/src/test/java/com/pm/wordi/WordiApplicationTests.java
Labels: 🚖 Feature, 🛠 BE

#56 Feat: [#55] Entity 생성 및 연관관계 매핑
  server/wordi/src/main/java/com/pm/wordi/domain/BaseEntity.java
  server/wordi/src/main/java/com/pm/wordi/domain/BaseStatus.java
  server/wordi/src/main/java/com/pm/wordi/domain/Keyword.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentor/Mentor.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentor/MentorKeyword.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentor/MentorLevel.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentor/MentorSchedule.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentor/Week.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentoring/Mentoring.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentoring/MentoringStatus.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentoring/Payment.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentoring/PaymentStatus.java
  server/wordi/src/main/java/com/pm/wordi/domain/review/Review.java
  server/wordi/src/main/java/com/pm/wordi/domain/user/User.java
  server/wordi/src/main/java/com/pm/wordi/domain/user/UserKeyword.java
  server/wordi/src/main/java/com/pm/wordi/domain/user/UserLevel.java
Labels: 🚖 Feature, 🛠 BE

#58 Feat: [#57] JPA 관련 클래스 추가, User 회원가입 기초 틀 구현
  server/wordi/.gitignore
  server/wordi/build.gradle
  server/wordi/src/main/java/com/pm/wordi/commons/certification/AES128.java
  server/wordi/src/main/java/com/pm/wordi/commons/certification/Secret.java
  server/wordi/src/main/java/com/pm/wordi/commons/config/SecurityConfig.java
  server/wordi/src/main/java/com/pm/wordi/controller/UserApiController.java
  server/wordi/src/main/java/com/pm/wordi/controller/dto/UserDto.java
  server/wordi/src/main/java/com/pm/wordi/domain/user/User.java
  server/wordi/src/main/java/com/pm/wordi/domain/user/UserRepository.java
  server/wordi/src/main/java/com/pm/wordi/exception/user/certification/NotAuthorizedException.java
  server/wordi/src/main/java/com/pm/wordi/service/UserService.java
  server/wordi/src/main/java/com/pm/wordi/service/certification/JwtService.java
Labels: 🚖 Feature, 🛠 BE

#60 Feat: [#59] 공통 예외처리를 위한 Advice 생성 및 AES128 class 예외처리 작업
  server/wordi/.gitignore
  server/wordi/src/main/java/com/pm/wordi/commons/advice/ExceptionAdvice.java
  server/wordi/src/main/java/com/pm/wordi/commons/certification/AES128.java
  server/wordi/src/main/java/com/pm/wordi/commons/certification/Secret.java
  server/wordi/src/main/java/com/pm/wordi/commons/utils/constants/ResponseConstants.java
  server/wordi/src/main/java/com/pm/wordi/controller/dto/UserDto.java
  server/wordi/src/main/java/com/pm/wordi/exception/DecryptException.java
  server/wordi/src/main/java/com/pm/wordi/exception/EncryptException.java
  server/wordi/src/main/java/com/pm/wordi/service/UserService.java
  server/wordi/src/main/java/com/pm/wordi/service/certification/JwtService.java
Labels: 🚖 Feature, 🛠 BE

#64 Feat: [#61] 회원 로그인, 인증 관련 account API 구현
  server/wordi/src/main/java/com/pm/wordi/commons/advice/ExceptionAdvice.java
  server/wordi/src/main/java/com/pm/wordi/controller/UserApiController.java
  server/wordi/src/main/java/com/pm/wordi/controller/dto/UserDto.java
  server/wordi/src/main/java/com/pm/wordi/domain/user/UserRepository.java
  server/wordi/src/main/java/com/pm/wordi/exception/user/NoExistEmailException.java
  server/wordi/src/main/java/com/pm/wordi/exception/user/NotAuthorizedException.java
  server/wordi/src/main/java/com/pm/wordi/exception/user/NotMatchPasswordException.java
  server/wordi/src/main/java/com/pm/wordi/service/UserService.java
  server/wordi/src/main/java/com/pm/wordi/service/certification/JwtService.java
Labels: 🚖 Feature, 🛠 BE

#66 Feat: [#65] Interceptor를 활용한 로그인 인가 처리 구현
  server/wordi/src/main/java/com/pm/wordi/commons/advice/ExceptionAdvice.java
  server/wordi/src/main/java/com/pm/wordi/commons/annotation/Auth.java
  server/wordi/src/main/java/com/pm/wordi/commons/annotation/UnAuth.java
  server/wordi/src/main/java/com/pm/wordi/commons/config/WebConfig.java
  server/wordi/src/main/java/com/pm/wordi/commons/interceptor/LoginCheckInterceptor.java
  server/wordi/src/main/java/com/pm/wordi/controller/UserApiController.java
  server/wordi/src/main/java/com/pm/wordi/domain/user/UserLevel.java
  server/wordi/src/main/java/com/pm/wordi/domain/user/UserRepository.java
  server/wordi/src/main/java/com/pm/wordi/exception/user/CertifiedException.java
  server/wordi/src/main/java/com/pm/wordi/exception/user/NoExistUserException.java
  server/wordi/src/main/java/com/pm/wordi/service/certification/JwtService.java
  server/wordi/src/main/java/com/pm/wordi/service/certification/SessionLoginService.java
Labels: 🚖 Feature, 🛠 BE

#67 Feat: [#62] 회원 정보 관련 account API 구현
  server/wordi/src/main/java/com/pm/wordi/commons/utils/constants/ResponseConstants.java
  server/wordi/src/main/java/com/pm/wordi/controller/UserApiController.java
  server/wordi/src/main/java/com/pm/wordi/controller/dto/UserDto.java
  server/wordi/src/main/java/com/pm/wordi/domain/user/User.java
  server/wordi/src/main/java/com/pm/wordi/service/UserService.java
Labels: 🚖 Feature, 🛠 BE

#70 Fix: [#69] BaseEntity BaseTimeEntity로 수정. EnableJpaAuditing 추가
  server/wordi/src/main/java/com/pm/wordi/WordiApplication.java
  server/wordi/src/main/java/com/pm/wordi/domain/BaseTimeEntity.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentor/Mentor.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentoring/Mentoring.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentoring/Payment.java
  server/wordi/src/main/java/com/pm/wordi/domain/review/Review.java
  server/wordi/src/main/java/com/pm/wordi/domain/user/User.java
Labels: 🕷 bug, 🛠 BE

#72 Feat: [#38] 멘토 목록 페이지(MentorListPage) Header 컴포넌트 추가
  client/package.json
  client/src/App.tsx
  client/src/assets/icons/Pin.svg
  client/src/assets/icons/hambuger.svg
  client/src/components/Main/Header.tsx
  client/src/components/MentorList/Header.tsx
  client/src/components/common/BottomTabBar.tsx
  client/src/components/common/TopNavbar.tsx
  client/src/components/icon/ActiveNoficiationIcon.tsx
  client/src/components/icon/PinIcon.tsx
  client/src/pages/MentorListPage.tsx
  client/src/utils/routes.ts
Labels: 🚖 Feature, 🌐 FE, ⚙ Component

#73 Feat: [#38] MentorListCard 컴포넌트 추가
  client/src/components/MentorList/MentorListCard.tsx
  client/src/components/common/Tag.tsx
  client/src/pages/MentorListPage.tsx
Labels: 🚖 Feature, 🌐 FE, ⚙ Component

#75 Feat: [#68] 구현한 User Api Validation 처리
  server/wordi/build.gradle
  server/wordi/src/main/java/com/pm/wordi/commons/advice/ExceptionAdvice.java
  server/wordi/src/main/java/com/pm/wordi/commons/interceptor/LoginCheckInterceptor.java
  server/wordi/src/main/java/com/pm/wordi/controller/UserApiController.java
  server/wordi/src/main/java/com/pm/wordi/controller/dto/UserDto.java
  server/wordi/src/main/java/com/pm/wordi/service/UserService.java
Labels: 🚖 Feature, 🛠 BE

#77 Feat: [#76] User Entity Keyword 로직 추가
  server/wordi/src/main/java/com/pm/wordi/controller/UserApiController.java
  server/wordi/src/main/java/com/pm/wordi/controller/dto/UserDto.java
  server/wordi/src/main/java/com/pm/wordi/domain/Keyword.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentor/Mentor.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentor/MentorKeyword.java
  server/wordi/src/main/java/com/pm/wordi/domain/user/User.java
  server/wordi/src/main/java/com/pm/wordi/domain/user/UserKeyword.java
  server/wordi/src/main/java/com/pm/wordi/domain/user/UserKeywordRepository.java
  server/wordi/src/main/java/com/pm/wordi/service/UserService.java
Labels: 🚖 Feature, 🛠 BE

#78 Feat: [#63] 유저 프로필 API 구현
  server/wordi/src/main/java/com/pm/wordi/controller/UserApiController.java
  server/wordi/src/main/java/com/pm/wordi/controller/dto/UserDto.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentor/Mentor.java
  server/wordi/src/main/java/com/pm/wordi/domain/user/User.java
  server/wordi/src/main/java/com/pm/wordi/domain/user/UserKeyword.java
  server/wordi/src/main/java/com/pm/wordi/domain/user/UserKeywordRepository.java
  server/wordi/src/main/java/com/pm/wordi/domain/user/UserRepository.java
  server/wordi/src/main/java/com/pm/wordi/service/UserService.java
Labels: 🚖 Feature, 🛠 BE

#83 Feat: [#81] 멘토 리스트 페이지 완성
  client/package.json
  client/src/components/MentorList/Body.tsx
  client/src/components/MentorList/Header.tsx
  client/src/pages/MentorListPage.tsx
Labels: 🚖 Feature, 🌐 FE

#84 Feat: [#79] 멘토 등록 및 프로필 관리 API 구현
  server/wordi/src/main/java/com/pm/wordi/commons/advice/ExceptionAdvice.java
  server/wordi/src/main/java/com/pm/wordi/commons/utils/constants/ResponseConstants.java
  server/wordi/src/main/java/com/pm/wordi/controller/MentorApiController.java
  server/wordi/src/main/java/com/pm/wordi/controller/dto/MentorDto.java
  server/wordi/src/main/java/com/pm/wordi/controller/dto/UserDto.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentor/Mentor.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentor/MentorKeyword.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentor/MentorKeywordRepository.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentor/MentorLevel.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentor/MentorRepository.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentor/MentorSchedule.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentor/MentorScheduleRepository.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentor/Week.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentoring/Mentoring.java
  server/wordi/src/main/java/com/pm/wordi/domain/review/Review.java
  server/wordi/src/main/java/com/pm/wordi/domain/user/User.java
  server/wordi/src/main/java/com/pm/wordi/domain/user/UserKeyword.java
  server/wordi/src/main/java/com/pm/wordi/domain/user/UserRepository.java
  server/wordi/src/main/java/com/pm/wordi/exception/mentor/NoExistMentorException.java
  server/wordi/src/main/java/com/pm/wordi/service/MentorService.java
  server/wordi/src/main/java/com/pm/wordi/service/UserService.java
Labels: 🚖 Feature, 🛠 BE

#88 Feat: [#85] 멘토 프로필 리스트, 멘토 프로필 상세 조회 API
  server/wordi/src/main/java/com/pm/wordi/commons/advice/ExceptionAdvice.java
  server/wordi/src/main/java/com/pm/wordi/controller/MentorApiController.java
  server/wordi/src/main/java/com/pm/wordi/controller/dto/MentorDto.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentor/Mentor.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentor/MentorRepository.java
  server/wordi/src/main/java/com/pm/wordi/exception/mentor/ExistMentorException.java
  server/wordi/src/main/java/com/pm/wordi/exception/mentor/NoExistMentoringProfileException.java
  server/wordi/src/main/java/com/pm/wordi/service/MentorService.java
Labels: 🚖 Feature, 🛠 BE

#89 Feat: [#86] 멘토링 신청, 조회 관련 API 구현
  server/wordi/src/main/java/com/pm/wordi/commons/advice/ExceptionAdvice.java
  server/wordi/src/main/java/com/pm/wordi/controller/MentorApiController.java
  server/wordi/src/main/java/com/pm/wordi/controller/MentoringApiController.java
  server/wordi/src/main/java/com/pm/wordi/controller/dto/MentorDto.java
  server/wordi/src/main/java/com/pm/wordi/controller/dto/MentoringDto.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentor/Mentor.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentor/MentorRepository.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentoring/Mentoring.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentoring/MentoringRepository.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentoring/Payment.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentoring/PaymentRepository.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentoring/PaymentStatus.java
  server/wordi/src/main/java/com/pm/wordi/domain/user/User.java
  server/wordi/src/main/java/com/pm/wordi/exception/mentoring/EqualUserMentorException.java
  server/wordi/src/main/java/com/pm/wordi/service/MentorService.java
  server/wordi/src/main/java/com/pm/wordi/service/MentoringService.java
Labels: 🚖 Feature, 🛠 BE

#90 Feat: [#87] 멘토링 승락, 거절 및 예약 취소 API
  server/wordi/src/main/java/com/pm/wordi/commons/advice/ExceptionAdvice.java
  server/wordi/src/main/java/com/pm/wordi/controller/MentoringApiController.java
  server/wordi/src/main/java/com/pm/wordi/controller/dto/MentoringDto.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentoring/Mentoring.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentoring/MentoringRepository.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentoring/Payment.java
  server/wordi/src/main/java/com/pm/wordi/exception/mentoring/NoExistMentoringException.java
  server/wordi/src/main/java/com/pm/wordi/exception/mentoring/NoExistPaymentException.java
  server/wordi/src/main/java/com/pm/wordi/service/MentoringService.java
Labels: 🚖 Feature, 🛠 BE

#93 Feat: [#92] 메인 페이지 초기 API 구현
  server/wordi/src/main/java/com/pm/wordi/controller/CommonApiController.java
  server/wordi/src/main/java/com/pm/wordi/controller/dto/CommonDto.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentoring/MentoringRepository.java
  server/wordi/src/main/java/com/pm/wordi/domain/review/ReviewRepository.java
  server/wordi/src/main/java/com/pm/wordi/service/CommonService.java
Labels: 🚖 Feature, 🛠 BE

#95 Feat: [#94] MySql 패키지 설치 및 RDS 연결 설정
  server/wordi/build.gradle
Labels: 🚖 Feature, 🛠 BE

#96 Feat: [#39] DropdownMenu 컴포넌트 추가
  client/src/components/common/DropdownMenu.tsx
Labels: 🚖 Feature, 🌐 FE, ⚙ Component

#99 Feat: [#98] Recoil 설치, 초기 환경 설정
  client/package-lock.json
  client/package.json
  client/src/atoms/atoms.ts
Labels: 🚖 Feature, 🌐 FE

#102 Feat: [#100] 월별, 키워드별, 관심 국가별 DropdownMenu 컴포넌트 추가 (멘토 리스트 페이지)
  client/src/assets/icons/down.svg
  client/src/assets/icons/refresh.svg
  client/src/components/MentorList/Body.tsx
  client/src/components/MentorList/KeywordFilter.tsx
  client/src/components/MentorList/MonthFilter.tsx
  client/src/components/MentorList/NationFilter.tsx
  client/src/components/icon/DownIcon.tsx
  client/src/components/icon/RefreshIcon.tsx
  client/src/styles/GlobalStyles.ts
Labels: 🚖 Feature, 🌐 FE

#103 Feat: [#101] 기간, 키워드, 국가별 필터링 기능 추가 (멘토 리스트 페이지)
  client/src/atoms/atoms.ts
  client/src/components/MentorList/Body.tsx
  client/src/components/MentorList/KeywordFilter.tsx
  client/src/components/MentorList/MentorListCard.tsx
  client/src/components/MentorList/MonthFilter.tsx
  client/src/components/MentorList/NationFilter.tsx
  client/src/components/icon/RefreshIcon.tsx
  client/src/constants/tempMentorData.ts
Labels: 🚖 Feature, 🌐 FE, ⚙ Component

#105 Style: [#104] DropdownMenu 컴포넌트 스타일 수정
  client/src/components/common/DropdownMenu.tsx
Labels: 🕷 bug, 🌐 FE, ⚙ Component

#107 Fix: [#106] MentorReviewPage를 MentorDetailPage로 변경, 라우트 추가 변경
  client/src/App.tsx
  client/src/pages/MentorDetailPage.tsx
  client/src/pages/MentorProfilePage.tsx
  client/src/utils/routes.ts
Labels: 🕷 bug, 🌐 FE

#108 Feat: [#17] PaymentButton 컴포넌트 추가
  client/src/assets/icons/check.svg
  client/src/components/MentorDetail/Footer.tsx
  client/src/components/MentorDetail/Header.tsx
  client/src/components/MentorDetail/Introduction.tsx
  client/src/components/MentorDetail/PaymentButton.tsx
  client/src/components/MentorDetail/Review.tsx
  client/src/components/common/BottomTabBar.tsx
  client/src/components/icon/CheckIcon.tsx
  client/src/pages/MentorDetailPage.tsx
  client/src/pages/MentorProfilePage.tsx
  client/src/styles/Theme.ts
  client/src/utils/routes.ts
Labels: 🚖 Feature, 🌐 FE, ⚙ Component

#110 Feat: [#109] 멘토 프로필 페이지 Footer 추가
  client/src/components/MentorDetail/Footer.tsx
  client/src/components/MentorDetail/PaymentButton.tsx
Labels: 🚖 Feature, 🌐 FE

#112 Feat: [#111] Nation 컴포넌트 추가
  client/src/assets/img/nations/Argentina.png
  client/src/assets/img/nations/Australia.png
  client/src/assets/img/nations/Canada.png
  client/src/assets/img/nations/Denmark.png
  client/src/assets/img/nations/France.png
  client/src/assets/img/nations/Germany.png
  client/src/assets/img/nations/Hongkong.png
  client/src/assets/img/nations/Italy.png
  client/src/assets/img/nations/Japan.png
  client/src/assets/img/nations/UK.png
  client/src/components/common/Nation.tsx
Labels: 🚖 Feature, 🌐 FE, ⚙ Component

#117 각 페이지 별 국가 아이콘, 멘토 프로필 이미지 추가
  client/src/assets/img/example_profile_img.png
  client/src/assets/img/mentorImage/airport.jpg
  client/src/assets/img/mentorImage/airport.png
  client/src/assets/img/mentorImage/beach.png
  client/src/assets/img/mentorImage/girl.png
  client/src/assets/img/mentorImage/landscape.jpg
  client/src/assets/img/mentorImage/marching_band.png
  client/src/assets/img/mentorImage/spread_arms.png
  client/src/assets/img/nations/UK.png
  client/src/components/Main/Countries.tsx
  client/src/components/Main/Flag.tsx
  client/src/components/Main/PopularMentors.tsx
  client/src/components/Main/ProfileCard.tsx
  client/src/components/MentorColumn/Header.tsx
  client/src/components/MentorColumn/MentorProfileCard.tsx
  client/src/components/MentorDetail/Header.tsx
  client/src/components/MentorList/Body.tsx
  client/src/components/MentorList/MentorListCard.tsx
  client/src/components/common/BreadCrumb.tsx
  client/src/components/common/Nation.tsx
  client/src/components/common/ProfileImage.tsx
  client/src/components/common/Tag.tsx
  client/src/constants/dummy.ts
  client/src/constants/tempMentorData.ts
  client/src/pages/MentorDetailPage.tsx
Labels: 🚖 Feature, 🌐 FE

#118 Fix: [#114] 필터링 기능 정상 동작하도록 수정
  client/src/components/MentorList/KeywordFilter.tsx
  client/src/components/MentorList/MonthFilter.tsx
  client/src/components/MentorList/NationFilter.tsx
Labels: 🕷 bug, 🌐 FE

#120 Feat: [#116] [#119] 멘토 프로필 페이지 디자인 수정
  client/src/assets/icons/smile.svg
  client/src/assets/img/banner/column_banner_1.png
  client/src/assets/img/banner/column_banner_2.png
  client/src/assets/img/banner/column_banner_3.jpg
  client/src/components/Application/Bottom.tsx
  client/src/components/Application/Header.tsx
  client/src/components/MentorColumn/ColumnDetail.tsx
  client/src/components/MentorDetail/Footer.tsx
  client/src/components/MentorDetail/Header.tsx
  client/src/components/MentorDetail/Introduction.tsx
  client/src/components/MentorDetail/PaymentButton.tsx
  client/src/components/MentorDetail/Reviews.tsx
  client/src/components/MentorList/MentorListCard.tsx
  client/src/components/common/BannerImage.tsx
  client/src/components/common/Nation.tsx
  client/src/components/common/ReviewCard.tsx
  client/src/components/common/Tag.tsx
  client/src/components/icon/SmileIcon.tsx
  client/src/components/icon/UKIcon.tsx
  client/src/constants/dummy.ts
  client/src/pages/MentorDetailPage.tsx
  client/src/styles/GlobalStyles.ts
Labels: 🕷 bug, 🌐 FE, 🖌Style

#122 Style: [#121] 멘토링 신청 페이지 스타일 수정
  client/src/assets/icons/cancel.svg
  client/src/components/Application/Bottom.tsx
  client/src/components/Application/Header.tsx
  client/src/components/Application/ScheduleApplication.tsx
  client/src/components/icon/CancelIcon.tsx
  client/src/pages/ApplicationPage.tsx
  client/src/pages/MentorDetailPage.tsx
  client/src/styles/GlobalStyles.ts
Labels: 🌐 FE, 🖌Style

#128 Style: [#124] 멘토 리스트 페이지 스타일 수정
  client/src/assets/icons/mentorList_hamburger.svg
  client/src/assets/icons/mentorList_notification.svg
  client/src/components/MentorList/Header.tsx
  client/src/components/icon/ActiveNoficiationIcon.tsx
  client/src/components/icon/TempHamburgerIcon.tsx
  client/src/components/icon/TempNotificationIcon.tsx
  client/src/pages/MentorListPage.tsx
Labels: 🕷 bug, 🌐 FE, 🖌Style

#129 Feat: [#74] 로고 변경 (좌측 상단 탭)
  client/public/favicon.ico
  client/public/index.html
  client/public/logo.svg
Labels: 🚖 Feature, 🌐 FE

#130 Feat: [#127] 동적 라우팅 설정, 국가 아이콘 클릭시 필터링된 상태로 페이지 이동
  client/src/components/Main/Countries.tsx
  client/src/components/Main/Flag.tsx
  client/src/components/MentorList/Body.tsx
  client/src/components/MentorList/MentorListCard.tsx
  client/src/constants/dummy.ts
  client/src/utils/routes.ts
Labels: 🚖 Feature, 🌐 FE

#134 Style: [#132] 메인 페이지 스타일 수정
  client/src/assets/icons/logo.svg
  client/src/components/Application/Bottom.tsx
  client/src/components/Main/Flag.tsx
  client/src/components/common/Carousel.tsx
  client/src/components/common/TopNavbar.tsx
  client/src/components/icon/ActiveNoficiationIcon.tsx
  client/src/components/icon/ActiveReviewIcon.tsx
  client/src/components/icon/HomeIcon.tsx
  client/src/components/icon/LogoIcon.tsx
  client/src/components/icon/LoveIcon.tsx
  client/src/components/icon/MentorIcon.tsx
  client/src/components/icon/MessageIcon.tsx
  client/src/components/icon/MyIcon.tsx
  client/src/components/icon/ReviewIcon.tsx
  client/src/components/icon/SmileIcon.tsx
Labels: 🕷 bug, 🌐 FE, 🖌Style

#136 Feat: [#135] 화면 전환 시 스크롤 맨 위로 고정
  client/src/components/common/ScrollToTop.tsx
  client/src/index.tsx
Labels: 🚖 Feature, 🌐 FE, ⚙ Component

#138 Style: [#137] DropdownMenu 컴포넌트 스타일 수정
  client/src/assets/icons/down.svg
  client/src/components/common/DropdownMenu.tsx
  client/src/components/icon/DownIcon.tsx
  client/src/components/icon/PinIcon.tsx
  client/src/components/icon/RefreshIcon.tsx
Labels: 🕷 bug, 🌐 FE, 🖌Style

#140 Style: [#139] BottomTabBar 컴포넌트 아이콘 색상, 굵기 수정
  client/src/assets/icons/home.svg
  client/src/assets/icons/mentor.svg
  client/src/assets/icons/my.svg
  client/src/assets/icons/order.svg
  client/src/assets/icons/review.svg
  client/src/components/MentorList/Body.tsx
  client/src/components/icon/ActiveReviewIcon.tsx
  client/src/components/icon/HomeIcon.tsx
  client/src/components/icon/MentorIcon.tsx
  client/src/components/icon/MyIcon.tsx
  client/src/components/icon/OrderIcon.tsx
  client/src/components/icon/ReviewIcon.tsx
Labels: 🌐 FE, 🖌Style

#143 Style: [#141] 멘토 컬럼, 신청 페이지 스타일 수정
  client/src/assets/icons/left.svg
  client/src/assets/icons/market.svg
  client/src/assets/icons/message.svg
  client/src/components/Application/Bottom.tsx
  client/src/components/Application/Header.tsx
  client/src/components/Application/ScheduleApplication.tsx
  client/src/components/Main/ProfileCard.tsx
  client/src/components/MentorColumn/Footer.tsx
  client/src/components/MentorColumn/Header.tsx
  client/src/components/MentorDetail/Footer.tsx
  client/src/components/MentorList/Body.tsx
  client/src/components/MentorList/MentorListCard.tsx
  client/src/components/common/BottomTabBar.tsx
  client/src/components/common/BreadCrumb.tsx
  client/src/components/common/Carousel.tsx
  client/src/components/icon/LeftIcon.tsx
  client/src/components/icon/LoveIcon.tsx
  client/src/components/icon/MarketIcon.tsx
  client/src/components/icon/MessageIcon.tsx
  client/src/pages/ApplicationPage.tsx
  client/src/pages/MentorProfilePage.tsx
Labels: 🌐 FE, 🖌Style

#146 Fix: [#145] CORS 설정 및 Preflight Request 로직 추가
  server/wordi/src/main/java/com/pm/wordi/commons/config/WebConfig.java
  server/wordi/src/main/java/com/pm/wordi/commons/interceptor/LoginCheckInterceptor.java
Labels: 🕷 bug, 🛠 BE

#147 서버와 연결, API 요청 후 멘토 필터링 페이지에 적용
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/atoms/atoms.ts
  client/src/components/Application/Header.tsx
  client/src/components/Main/Countries.tsx
  client/src/components/MentorDetail/Footer.tsx
  client/src/components/MentorList/Body.tsx
  client/src/components/MentorList/KeywordFilter.tsx
  client/src/components/MentorList/MentorListCard.tsx
  client/src/components/MentorList/MonthFilter.tsx
  client/src/components/MentorList/NationFilter.tsx
  client/src/components/common/BottomTabBar.tsx
  client/src/constants/routes.ts
  client/src/hooks/useFetch.ts
  client/src/index.tsx
  client/src/utils/matchStringExact.ts
  client/src/utils/monthTypeConverter.ts
Labels: 🚖 Feature, 🌐 FE

#148 Fix: [#145] github 배포 url CORS 설정에 추가
  server/wordi/src/main/java/com/pm/wordi/commons/config/WebConfig.java
Labels: 🕷 bug, 🛠 BE

#149 Fix: [#145] CORS 경로URL 수정
  server/wordi/src/main/java/com/pm/wordi/commons/config/WebConfig.java
Labels: 🕷 bug, 🛠 BE

#150 Fix: [#145] CORS 설정 임시 허용
  server/wordi/src/main/java/com/pm/wordi/commons/config/WebConfig.java
Labels: 🕷 bug, 🛠 BE

#154 SVG 아이콘의 stroke-width 속성을 strokeWidth로 변경
  client/src/components/icon/ActiveNoficiationIcon.tsx
  client/src/components/icon/DownIcon.tsx
  client/src/components/icon/HomeIcon.tsx
  client/src/components/icon/LeftIcon.tsx
  client/src/components/icon/LoveIcon.tsx
  client/src/components/icon/MarketIcon.tsx
  client/src/components/icon/MessageIcon.tsx
  client/src/components/icon/PinIcon.tsx
  client/src/components/icon/RefreshIcon.tsx
  client/src/components/icon/ReviewIcon.tsx
  client/src/components/icon/SmileIcon.tsx
  client/src/constants/dummy.ts
Labels: 🕷 bug, 🌐 FE

#155 Feat: [#133] FlatList 공통 컴포넌트 추가, 중복되는 스타일 컴포넌트 FlatList 컴포넌트로 중복 제거
  client/src/components/Main/Banners.tsx
  client/src/components/Main/Footer.tsx
  client/src/components/Main/MentiReviews.tsx
  client/src/components/Main/PopularMentors.tsx
  client/src/components/MentorDetail/Introduction.tsx
  client/src/components/MentorDetail/Reviews.tsx
  client/src/components/MentorList/Body.tsx
  client/src/components/MentorList/Header.tsx
  client/src/components/common/FlatList.tsx
Labels: 🛠 Refactoring, 🌐 FE, ⚙ Component

#158 Style: [#157] MentorDetailPage 더보기 > 추가
  client/src/assets/icons/right.svg
  client/src/components/MentorDetail/Introduction.tsx
  client/src/components/MentorDetail/Reviews.tsx
  client/src/components/icon/RightIcon.tsx
Labels: 🕷 bug, 🌐 FE, 🖌Style

#159 Refactor: [#151] 검색 필터링 기능 QueryDSL로 리팩토링
  server/wordi/build.gradle
  server/wordi/src/main/java/com/pm/wordi/controller/MentorApiController.java
  server/wordi/src/main/java/com/pm/wordi/controller/dto/MentorDto.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentor/MentorRepository.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentor/MentorRepositoryCustom.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentor/MentorRepositoryImpl.java
  server/wordi/src/main/java/com/pm/wordi/service/MentorService.java
Labels: 🛠 Refactoring, 🛠 BE

#160 Fix: [#156] map 메서드를 사용해 요소를 렌더링 할 때 key값 추가하기
  client/public/manifest.json
  client/src/components/Main/IconReviewCard.tsx
  client/src/components/Main/MentiReviews.tsx
  client/src/components/MentorColumn/ColumnDetail.tsx
  client/src/components/MentorDetail/Header.tsx
  client/src/components/MentorDetail/Reviews.tsx
  client/src/components/MentorList/MentorListCard.tsx
  client/src/components/common/ReviewCard.tsx
  client/src/components/common/Tag.tsx
  client/src/components/common/Title.tsx
  client/src/constants/dummy.ts
Labels: 🕷 bug, 🌐 FE

#163 Feat: [#161] Storybook 설치, 초기 환경 설정
  client/.storybook/main.js
  client/.storybook/preview.js
  client/package-lock.json
  client/package.json
  client/src/stories/Button.stories.tsx
  client/src/stories/Button.tsx
  client/src/stories/Header.stories.tsx
  client/src/stories/Header.tsx
  client/src/stories/Introduction.stories.mdx
  client/src/stories/Page.stories.tsx
  client/src/stories/Page.tsx
  client/src/stories/assets/code-brackets.svg
  client/src/stories/assets/colors.svg
  client/src/stories/assets/comments.svg
  client/src/stories/assets/direction.svg
  client/src/stories/assets/flow.svg
  client/src/stories/assets/plugin.svg
  client/src/stories/assets/repo.svg
  client/src/stories/assets/stackalt.svg
  client/src/stories/button.css
  client/src/stories/header.css
  client/src/stories/page.css
Labels: 🚖 Feature, 🌐 FE

#165 Feat: [#91] 리뷰 CRUD API 구현
  server/wordi/src/main/java/com/pm/wordi/commons/advice/ExceptionAdvice.java
  server/wordi/src/main/java/com/pm/wordi/controller/CommonApiController.java
  server/wordi/src/main/java/com/pm/wordi/controller/MentorApiController.java
  server/wordi/src/main/java/com/pm/wordi/controller/MentoringApiController.java
  server/wordi/src/main/java/com/pm/wordi/controller/ReviewApiController.java
  server/wordi/src/main/java/com/pm/wordi/controller/UserApiController.java
  server/wordi/src/main/java/com/pm/wordi/controller/dto/ReviewDto.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentor/repository/MentorRepository.java
  server/wordi/src/main/java/com/pm/wordi/domain/mentoring/repository/MentoringRepository.java
  server/wordi/src/main/java/com/pm/wordi/domain/review/entity/Review.java
  server/wordi/src/main/java/com/pm/wordi/domain/review/repository/ReviewRepository.java
  server/wordi/src/main/java/com/pm/wordi/exception/review/NoExistReviewException.java
  server/wordi/src/main/java/com/pm/wordi/exception/review/NoMatchUserReviewException.java
  server/wordi/src/main/java/com/pm/wordi/service/ReviewService.java
Labels: 🚖 Feature, 🛠 BE
